


operator:
  # -- By default, operator converts prometheus-operator objects.
  disable_prometheus_converter: true


resources:
  limits:
    cpu: 120m
    memory: 320Mi
  requests:
    cpu: 10m
    memory: 120Mi


admissionWebhooks:
  enabled: true
  certManager:
    enabled: true

serviceMonitor:
  enabled: true
