---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: vm
spec:
  url: https://victoriametrics.github.io/helm-charts/
  interval: 1h
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vmoperator
spec:
  chart:
    spec:
      chart: victoria-metrics-k8s-stack
      version: '0.19.0'
      sourceRef:
        kind: HelmRepository
        name: vm
  interval: 1h
  releaseName: vm
