apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAuth
metadata:
  name: vm
spec:
  selectAllByDefault: true
  userNamespaceSelector: {}
  userSelector: {}
  ingress:
    class_name: traefik # <-- change this to your ingress-controller
    host: vm.hamisoke.com # <-- change this to your domain
