---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adpy
  labels:
    app: adpy-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adpy-backend
  template:
    metadata:
      labels:
        app: adpy-backend
    spec:
      containers:
      - name: service
        image: ghcr.io/sorend/ad-py:0.1.2
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 50m
            memory: 100Mi
          requests:
            cpu: 5m
            memory: 50Mi
        envFrom:
          - secretRef:
              name: adpy-secret
        volumeMounts:
          - name: data-volume
            mountPath: /data
            readOnly: false
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
      volumes:
        - name: data-volume
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: adpy
  labels:
    app: adpy-backend
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app: adpy-backend
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: adpy
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`vvv.atmakuridavidsen.com`)
      kind: Rule
      services:
        - name: adpy
          port: 80
  tls:
    secretName: adpy-cert
