---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: adpy-cert
spec:
  secretName: adpy-cert
  dnsNames:
    - xyz.atmakuridavidsen.com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
