---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adpy
  labels:
    app: adpy-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adpy-server
  template:
    metadata:
      labels:
        app: adpy-server
    spec:
      containers:
      - name: service
        image: ghcr.io/sorend/ad-py:0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "50m"
            memory: "100Mi"
          requests:
            cpu: "5m"
            memory: "50Mi"
        env:
        - name: FLICKR_API_KEY
          valueFrom:
            secretKeyRef:
              name: adpy-secret
              key: FLICKR_API_KEY
        - name: FLICKR_USERID
          valueFrom:
            secretKeyRef:
              name: adpy-secret
              key: FLICKR_USERID
        - name: YOUTUBE_CHANNEL
          valueFrom:
            secretKeyRef:
              name: adpy-secret
              key: YOUTUBE_CHANNEL
        - name: YOUTUBE_DEVELOPER_KEY
          valueFrom:
            secretKeyRef:
              name: adpy-secret
              key: YOUTUBE_DEVELOPER_KEY
        volumeMounts:
          - name: data-volume
            mountPath: /data
            readOnly: false
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
      volumes:
        - name: data-volume
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: adpy
  labels:
    app: adpy-server
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app: adpy-server
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: adpy
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - vvv.atmakuridavidsen.com
    secretName: adpy-tls
  rules:
  - host: vvv.atmakuridavidsen.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: adpy
            port:
              number: 80
