apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: slack-webhook
  namespace: adpy
spec:
  encryptedData:
    address: AgCyt2z3PD20KTKd4/kZlPJUMuNr5Gea50TLjlv8WL5NSrGSODlnJ8S6OxNvo2A3XWhjDrR8BDPl9rnEKWl53rIhukSa87fPfoY3BF2VCOUnK9rbmYxBUD3XdEWxAxALOH1KwC/2XPbQDmR8N0Z896ULC5wYG6fvFDU5NBFUf3E4Z8VoRZ3LDlulE+tRXcuiTCNigcttWUZWgzT9+Da64xhtzpCITD7MGdGl6dlsvqtOeYM/pW3vmO4E50lgSuv7byyEph5n8lXGiJ5LxOkfGEdmwo3jza/MfI7VjF0mKpFoaUr6pmZrqGZsCRU0k2vGmB8TGn6qaVE98ZYqTrxfx1JW5mV0Ksj1AZys5kTo8lFMBHgk8px6J25KOkY9fsxd7xQyyCWI0wdJ6SlIujm3OmTQD27Vx4EIi7RXg3Knd/SCzUlcRa3vEJQzY2303rJ4kZ+e2lKt7U20MY7G2cn4Uwcz2Qi/+RZoVMk9ZVFF2ot2MDDpWsPpyuk3vDUz8iYGNokva/NZzGBFZMZ6XlwMQEP/M/w/0REGXX/7WHZoYy4fplC7CpWy1HncW82MD/MftP8YagGAcz6x4LJfwgGC1nkV3t+vynelsK2Ibzok2/5iECHcLcxlYxxWCWSPIMkwuTjzNDvHI1l7TlhNri3joWaLgnskcEogHTDzFEG3JRbdN8hWnm8wdWN4nctKVapWgiRmv+1rrrm7AM4Yu34VcVxCezyF9Pw+MFo8uzKZzHFdJ9+yoi6WQIUWPbu05g/YAx6gWf+Kb+HKG1FEVmxY21JWti7pzaXwazXB2RweWBp1
  template:
    metadata:
      creationTimestamp: null
      name: slack-webhook
      namespace: adpy

