apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: flickr-access-token
  namespace: adpy
spec:
  encryptedData:
    gokmp.yaml: AgCxkI1qQ2oz7GZ8kvP7mGvgGi01q711fskc0KEAB5bSjF5wsHuZAckJ6q1WM60FtdLdkC8SOYpq//WzLgjx3qFS0MeKGWYFOOcDOJLyc1FIJ9UXNN+GcR/3mkbySJwUYy0Epy89/VCxfrplD87N4DkhE6BlKVuC16SDP+Tc/5Rse41UCLtifzcjLlF+/TwkyY9yqUgRkYIAuxI4AgdhCom4f+IEsOsmA1n9NZ2RcMPwbnAHjIPUzCVvLmqMX//uyIGRxV6yLH5dGm+rIZkKxxv1ZP+/r2wUYxfHpN1wqmPF+i46/SUmWKcekVyTDidP1oHhEOS3G+ZOsinD43ug20RRrBfkGqPN/psX5LRzoxfbDZMhXw2nc2g2tT0HcJdn2qXk5kGyrLp+Tlp7PXc2Z+SMl2nJWHWYO1TKHbtzYcGS+znkmF0iGiyFmkwWXs7hdSiiNL0efmonSe1cRbyUzO6IJubY3oUoRiQTocIBozw8TiUszeDzeq3wUr5LmuUZJoI9SsYxnz8cCa7dSPNYC1kUJmD8kkVAjsCEiLmkQXw+6VYPOtguSnKXo0pVzHnStwSqaZ0qs03LZvf7KhYSPBC2Edo93tEN3hKMSQkwHVsB1z23Sq8yv+O6FNQ67XTGrMEmY9yQRy83+czSScna6sANKIctytTqOqg+D35ZzvlIvZnLkCO88Fp33Eg9trnHCtuLSliKv4Gl3TjHs0Nhy7xfHjSy0YqN6w2aGYJ3Bj9ug7P1PIYA6FKqSBgq/28oAPX86vJniTJ7d0dqyyfPc89MSkJM07N8coM+tPJ8rYMg
  template:
    metadata:
      creationTimestamp: null
      name: flickr-access-token
      namespace: adpy

