apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: slack-webhook
  namespace: adpy
spec:
  encryptedData:
    address: AgBptNguYvRSr3wC02CtWo1icwTdG05cv876XtFevL4hWHRU767REs7RoG9JGis9kVOKJq3fAGtpoERMqrUb3GFApl07vDYWNQb4nOGJRzyo4V0WObkkcn9r0by9jePZDbS1XkK1/cLN16kVTA2D9SzL+CL/MwnrhtEkZxbN8AIL2lX8J1ybrbKGBL5PbIb8UAXpiu6Pqy+CkwVXoyw6SjMQk/nIhQXZZIpSU9oqUxHbykvWTGYHnnRCRpwY2pGVZWAtSk93oE/qK03Q7ozN8r02xlz+sCVc1d5NaKxAHX72FsB0Iwrr6ykPuw0W/3cHhiMqZe02huq1ZU1RlspvcwL+hIQHh6LVrGjJPqwOw18AfqDvEpqzmEdFk8ONbr6i7653M+IBd3O475nBf35+KmDTjpYpfHIAIDizhcKZD9wXGncY74+6HxF+6bzAsJ+FTsHyWNRpjTpLRE/SIE1ZDQ+m40dtYG3bCtOcbtEwQ8HPDtwUQ5ESDETg4rtjLbx2qSOoyEJmmETvyVgbvtnnhXzQf/M9vY6sp3KYYYF0W9VFgRJgk4igcJoBotergWpllHsgXq+r/81A2ibb9wyQyRExA11/9oaP6N2m/SpgaclLqgaBFOOdu7mofMYSCBDmTZ91EtXsttp7jL3+HJ+Fp+QI2evOE5dvtZ6+X9u4iGuNqLDMaWaBNL4t9iwaWHzBWiG6Y5dmxZd4+W0h6N4wlPtaco5dHfWiRobftZ5ZgZSmJwtmKFmT9w/d2XkQA4tq19Upsg+hUca5okruiZJu20enSQvXKpZDRZ1pE2OwEqch
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: slack-webhook
      namespace: adpy

