apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: slack-webhook
  namespace: kube-system
spec:
  encryptedData:
    address: AgA4xLcYrjLojWh+HEFtl+zLmUwnqEtBMiPDhwwgtujkHLIyyfk/cxeUb1Zr5loP5v84BT0k9PCn94MgyyEWNr7AxukrTc5QPCG/y67y07CV73b0RlXqvvsMEp0ktIhj1Ic2dUp1QLQ+L0IxvbbFdqc/jXIlli+b8gVVt/yh8f0x670HZdrC1BTxrBPrnWnARP0HYU1e3Mja4ASjBsrxmRpAH+qGP4QbwNYjpMl4mNBJb0DrKsH32PyCW0TBm7dV2sYe+P62biFlLe+CK5r44S/r478gVqsAMP537/8IWc/gZwZ7efA4YLrwecwC1wVMod68ZTeV50gIuS/DTl/G8DpjW3oJ/3XLC5OMWRewB/vd1S8Arld5cC1U+kI4oVAKgRzpQnP24tBGZwxcJ0DKcwUP66YBqvNEH0QSLxydzn7U1yDy9H+3lXQWa4J+DLfrXHMrHkHaaAo2L8FIOUYtiR6JwQ4UX8uLvtK9t+HokTctlsrNwkHzfFN7Pcoq0FoMxkBTIgXSSxhFoAKbukcY0Pyodf+vQVmSWKuoQEkUhp4Zxjc/5z0Ac2VA0EIULhkwY2FFJa203kQqqmCE13n5DfPCFH1uenrPUdvs2sgrcPbkqjYkHSPfT/CGlMycXLq/KjI16XyvBgkQhyg/w+KXDAyN6l95Q9M0WIrKF/nN17aVXwLrGPmI2V5+KLp4uN9isst2iaRMmVThQppliY47Xje4BTNCt9ImpdRmyESN6IOPU1D7yexfUQGvfgXJwNTwCAYitFs185dkr84ZmoZ3a2FIz5/aBW21fKPHcWY8DK1d
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: slack-webhook
      namespace: kube-system

