apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: flickr-access-token
  namespace: adpy
spec:
  encryptedData:
    gokmp.yaml: AgAdwOx0afmBise5rxfeW/ufwd8IjiBEq6r8o2PdfzTUWkG+/KoB1hpiGhePikBsBRj11ov+xPgwPBDH92HtMwHbVZihw0h6eLP7PdIXygr2g/WWJifdqPkBh+dW5UYtZTQnl7/1ExVoRtvEOgmfjGQCejLDTjbAgxepKJqLnQQTErU3To7EdeSa44KZIlkPNj2RN4uU1vAKaoV12NgDpzGqWsA6pvd7Wwc8jqKu1GrqrzJ399dm4FOmTcWG7oykGgYig7EqNuY1nzLC01y9Y0GHd9YglLuqOIaNpg9rV7teltvUPwh+lxZcjMOAbf2MmULQZKespNWYNdgUpjNR+rXlHbx9SMTMXoTEo3dKA1vtzSi7YWq/EK3SrvL2R58gwgudMm3u1ZKbxBa2/GVaQMiqzjxUBIl7iqvt56y3GfkTYp8kksBowK4UPWqpBnOxn1Rbm+Ezs62TLxpU0l9T744ANcb9Ur50D+uEXGkoMOkLrmPXDeuMezTqpA6mGXc2/Mt79pA373PUY0/Kp7DuZMf6E2WnSiVfI9DcA+ACjTsF3GQmVTrJQqlQYzyW++gGRhOerSuUIwNbv/RAF5oWfO8DoRT0+/PC1NNGxsf6uaNRMWyo5RwPx9DWUDSzqtyxZdPMLEZrQ4pgI1rzTtgeddHJyuTCTJqfM0ix/bcPQFnYJiq9AQBqk1c/o8oj8neiiCPuqCZ8QGRGhrsfNSzg/MEP0f1J6J9ti4a4Ol0dZsWG41ro23eGXbGwOWM23p+PGZEaUOziYuBSkriCc0G4kEVM8vqU8pDTVtqmkgstHFT8
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: flickr-access-token
      namespace: adpy

