apiVersion: v1
kind: ConfigMap
metadata:
  name: web-config
data:
  svu.conf: |
    server {
      listen 80 default_server;
      server_name venkatadri.cs.svu-ac.in cs.svu-ac.in *.cs.svu-ac.in *.svu-ac.in svu-ac.in;
      location ~ ^/~([a-zA-Z0-9]+?)(/.*)?$ {
        autoindex on;
        index index.html;
        alias /home/$1/public_html$2;
      }
      location / {
        return 302 https://svuniversity.edu.in/;
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    app: web-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-server
  template:
    metadata:
      labels:
        app: web-server
    spec:
      nodeSelector:
        kubernetes.io/hostname: venkatadri
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
          - name: config-volume
            mountPath: /etc/nginx/conf.d
            readOnly: true
          - name: files-volume
            mountPath: /home/sorend/public_html
            readOnly: true
        resources:
          limits:
            cpu: 100m
            memory: 50Mi
      volumes:
        - name: config-volume
          configMap:
            name: web-config
        - name: files-volume
          hostPath:
            path: /home/sorend/public_html
            type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: web-service
  labels:
    app: web-server
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: web-server
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    traefik.ingress.kubernetes.io/redirect-entry-point: https
spec:
  tls:
  - hosts:
    - venkatadri.cs.svu-ac.in
    - www.cs.svu-ac.in
    - cs.svu-ac.in
    - www.svu-ac.in
    - svu-ac.in
    secretName: svu-ac-tls
  rules:
  - host: venkatadri.cs.svu-ac.in
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: web-service
            port:
              number: 80
  - host: www.cs.svu-ac.in
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: web-service
            port:
              number: 80
  - host: cs.svu-ac.in
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: web-service
            port:
              number: 80
  - host: www.svu-ac.in
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: web-service
            port:
              number: 80
  - host: svu-ac.in
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: web-service
            port:
              number: 80
