apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: victoriametrics
spec:
  interval: 5m
  chart:
    spec:
      chart: victoria-metrics-cluster
      sourceRef:
        kind: HelmRepository
        name: victoriametrics
  install:
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: victoria-metrics-values
