apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: victoriametrics
  namespace: flux-system
spec:
  url: https://victoriametrics.github.io/helm-charts/
  interval: 10m
