apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: victoriametrics
resources:
  - namespace.yaml
  - helmrepository.yaml
  - helmrelease.yaml
configMapGenerator:
  - name: victoriametrics-values
    files:
      - values.yaml=my-values.yaml
configurations:
  - kustomizeconfig.yaml
