apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: vm-operator-leader-election-role-2
  namespace: monitoring-system
rules:
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vm-operator-leader-election-rolebinding-2
  namespace: monitoring-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: vm-operator-leader-election-role-2
subjects:
- kind: ServiceAccount
  name: vm-operator-vm-operator
  namespace: monitoring-system
