apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: fluentd-k8s
  namespace: fluentd-k8s
spec:
  encryptedData:
    loggly.token: AgAahQtjCgTKRq2OJAvHQpaOoTq8Zyohg0t7HFaRxJnEyp8/4HFmVjhHqbb7H64wVy8WVuxmWU+r+rC3ldQ4iI/n/51cp7Jm31CbU//pOhbyBUubug0DWmu5xwypSFhV5XP3Lko1zpmJ+aGVqQyUDsKNdNDAWcL66pP2mxI1DbG1iMSWkbWcqzh4XpHqQFgZ4Smu01aaGYdGRT2Mm+f0ogD2D3RKwh4jfTe6Argg65t+ckm15ikgLCbHMk+mY1lAFPYQxEgneuuKUFYIUIu6SmlwZtScBMzFkuqxyDPb5PVO4A6ujw01d7Dg5MYj7yPD+4grcsEoD17ySUsHPth4xMegJMHW12PibsmIQLJN2+9g/oaZNVHxPGOpssZcc3DWrCg1eRC2JCKnluf00sqXJz3DjAP7TRY/FcFF0VwgJAXcIkDp5M2A8OhV4pt6mS8A8m+JiULTGT2QQTVwIfgTYhNgaBMXIWLCj61CR02cOT6+VLENyxEA8edyECEEXmMn6v4IJ33/d5Q7RFwN6RANU2ZHV1q/NmRDGNdGsThpY0alKEfS1hqWKXihRFKsKSkQrmsl5uYdscPTKG1FT6r6HJzNwSNAz9FZ/IEHzX5RDut3prUFdWlANeJNO/vr1GnS5Ome2l5XZGchA0LHGzRoM5EnNJiPKwwe1RYM4NWzae+nho6Zicuuope1oB+ovwn9cEZwOKxXscRTt6m9m0qt0Fzfbzi0k1aFOB/B/Sqy53TDVT+PavM=
    logzio.token: AgCIAjFjTaavhWXduaMY+qBOSq7RQMEfstcvRNObqkEo951gL3uAhLsZ/c4SM4kk97UBOfnh4GvzzKe3SsadRqtifqmX7vLCLa/WUtoDL3Vc3DQY7S//tKIKcEep1t9vIODz5zJBnny/KSC0xl6w97LO38i3GD0VsyEt+LpGoxGsTk5NltWcyhzHWuCKWQDzsY+Kie24a+Gz2T31JT8rpwwYzHVDIK+yl3Cy6qaSI1htMpOwDJ7iL8yyO2uDCyBIX2OuHP0AG3sxe4z7MJTqCHlw7E0CN22c5fODrx5okE0DHaZYb4PaILGqJS65T6OodnJ846repoOd6UkWBqU+kQZUaFxbw69RmDPjtRlx9b5MpzbnyBvqrh+13ZG0rOd10caZvQNep0qZSyK+UMoK+skLKf8v9csDfdW4Sivk2ypitm6GHvGsSWpiagbkMZlWoOD75ZRB/cH6lVRKbCNa4IE8qZxDB9rX+yo2FYIIExnFM83wgdq6m6UMQwE9c73VWjzV63ERWXo//+tB8gfYvIA+XJSM1QzBpnRAFhnOunyU7+8Mxkn026EyAZZcaCyQVFC1QfK5dGBSVsZCoNR59qhkrBn6acmdimA4oME7rN3RcbkX6eh3LLY56FW3msVsvAHj3IaY1baw5YU6ZfRRsuraxuUUMMS7/M+GuqfUjDgM3KowpcnjMc5oXIk7c1fqnEZXhVmQw2exF3grKmYPJIqyEJ+9Km2x2tccVYlDDjajOQ==
  template:
    metadata:
      creationTimestamp: null
      name: fluentd-k8s
      namespace: fluentd-k8s

