---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: athens
spec:
  interval: 5m
  url: https://athens.blob.core.windows.net/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: athens
spec:
  releaseName: athens
  chart:
    spec:
      chart: athens-proxy
      sourceRef:
        kind: HelmRepository
        name: athens
  interval: 5m
