---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: kube-prometheus
spec:
  interval: 10m0s
  ref:
    branch: main
  url: https://github.com/prometheus-operator/kube-prometheus.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: kube-prometheus-setup
spec:
  interval: 10m0s
  path: ./manifests/setup
  prune: true
  sourceRef:
    kind: GitRepository
    name: kube-prometheus
  validation: client
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: kube-prometheus
spec:
  interval: 10m0s
  path: ./
  prune: true
  dependsOn:
    - name: kube-prometheus-setup
  sourceRef:
    kind: GitRepository
    name: kube-prometheus
  validation: client
