---
apiVersion: v1
kind: Namespace
metadata:
  name: adpy
  annotations:
    kubernetes.io/contact-email: "sorend@gmail.com"
    fluentd/include: "true"
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: adpy
  namespace: adpy
spec:
  interval: 5m
  path: "./teams/adpy"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
